# Generated by Django 4.2.7 on 2025-09-26 07:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=300)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('hospital_name', models.CharField(max_length=300)),
                ('hospital_address', models.TextField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_days', models.CharField(help_text='e.g., Mon-Fri, Weekdays, etc.', max_length=100)),
                ('available_hours', models.CharField(help_text='e.g., 9:00 AM - 5:00 PM', max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('languages_spoken', models.CharField(help_text='Comma-separated languages', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['specialization'], name='doctors_doc_special_037046_idx'), models.Index(fields=['license_number'], name='doctors_doc_license_3eaac3_idx'), models.Index(fields=['is_active'], name='doctors_doc_is_acti_3a5153_idx'), models.Index(fields=['created_at'], name='doctors_doc_created_04e2c9_idx')],
            },
        ),
    ]
